name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main

jobs:
  Terraform:
    name: Terraform plan&apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: setpup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Terraform init
        run: terraform init

      - name: Terraform format check
        run: terraform fmt -check

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan

      - name: terraform apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve